### ISSUE TITLE
Remootio add on doesn't work with newest Home Assistant release

### ISSUE THREAD

**Issue by jwinston100** [sam43434/remootio#5]
Add on is broken in Home Assistant version 2022.12.0.

**Comment by yarafie** [comment]
This is error in homeassistant with hacs integration

2022-12-08 15:45:47.487 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package aioremootio==1.0.0a15: ERROR: Cannot install aioremootio==1.0.0a15 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip

**Comment by guidog66** [comment]
Indeed, I’m getting exactly the same error

**Comment by yarafie** [comment]
Just updated to latest in git repisitory and same problem but now aioremootio==1.0.0a17

**Comment by sokanaar** [comment]
**Still exists with 2022.12.1**

Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 17:43:37 (3 occurrences) 
Last logged: 17:43:54

Unable to install package aioremootio==1.0.0a17: ERROR: Cannot install aioremootio==1.0.0a17 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**I tried upgrading pip after sshing into the container and all went fine, but the next start of home assistant gave me the following:**

Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 17:40:55 (3 occurrences) 
Last logged: 17:41:08

Unable to install package aioremootio==1.0.0a17: ERROR: Cannot install aioremootio==1.0.0a17 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**From there we got into dependancy hell and that's where I downloaded the original container again until someone with more skill than me can have a look** :)

**Comment by AxDevl** [comment]
+1 same problem with me.

Te be honest, with this new release, most of my integrations stop working until an update was released.

**Comment by yarafie** [comment]
homeassistant new update 12.3 where they dropped aiohttp version from 3.8.3 to 3.8.1 for me has fixed this issue. All working now.

**Comment by sokanaar** [comment]
confirmed that 2022.12.3 has fixed the issue for me as well!

**Comment by AxDevl** [comment]
Also confirm that the new update has fixed the issue!

**Comment by yarafie** [comment]
12.4 released today remootio still working so you can upgrade

**Comment by jwinston100** [comment]
Thanks for letting us know. I was a bit unsure of whether to upgrade or not. Since everything is working now, I'll close this.
